MyPortFolios/MyPortFolio/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    
    path('',include('PortFolio.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

MyPortFolios/PortFolio/urls.py
from django.urls import path
from . import views
from .views import ProfileView
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [

    path('', views.login_view, name='login_view'),
    path('register/', views.register, name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('student/', views.student, name='student'),
    path('delete_profile_image/', views.delete_profile_image, name='delete_profile_image'),
    
    path('dashboard/',views.dashboard,name='dashboard'),
    path('activity/',views.activity,name='activity'),
    path('resume/',views.resume,name='resume'),

    path('waiting/', views.waiting_page, name='waiting_page'),
    path('home/', views.home, name='homepage'),
    
    # staff
    path('adminpage/', views.admin, name='adminpage'),
    path('decline/', views.decline_page, name='decline_page'),
    path('approve/<int:request_id>/', views.approve_request, name='approve_request'),
    path('decline/<int:request_id>/', views.decline_request, name='decline_request'),
    path('student_access_list/',views.student_list,name='student_list'),
    path('student/<int:student_id>/', views.student_details, name='student_details'),
    
    path("folder/<int:folderid>/",views.folder, name="folder"),
    path("addFolder/", views.addfolder, name="addfolder"),
    path("delete_folder/<int:folder_id>/", views.delete_folder, name="delete_folder"),
    path("delete_file/<int:file_id>/", views.delete_file, name="delete_file"),
    path('get_folder_file_data/', views.get_folder_file_data, name='get_folder_file_data'),
    path('get_folder_data/', views.get_folder_data, name='get_folder_data'),

    path('profile_visits/', views.profile_visits1, name='profile_visits1'),

    path('generate_qr_code/<str:generated_link>/', views.generate_qr_code, name='generate_qr_code'),
    path('logout/', views.logout_view, name='logout_view'),
    path('generate_link/', views.generate_visit_link, name='generate_visit'),
    path('profile_visits/<str:generated_link>/', views.profile_visits, name='profile_visits'),
    
 ]

    

MyPortFolios/PortFolio/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model


class User(AbstractUser):
    id = models.BigAutoField(primary_key=True) 
    ROLE_CHOICES = (
        ('admin', 'Admin'),
        ('student', 'Student'),
    )

    email = models.EmailField(unique=True)
    role = models.CharField(max_length=20, choices=ROLE_CHOICES, default='student')
    register_number = models.CharField(max_length=20, null=True, blank=True)
    request_approved = models.BooleanField(default=False)  
    request_declined = models.BooleanField(default=False)
    def __str__(self):
        return self.username


class RequestToAdmin(models.Model):
    student = models.ForeignKey(User, on_delete=models.CASCADE, related_name='requests_sent')
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Request from {self.student.username} at {self.timestamp}"

YEAR_CHOICES = (
    ("I year","I year"),
    ('II year','II year'),
    ('III year','III year'),
    ('IV year','IV year')
) 

Depat_CHOICES=(
    ('Artificial Intelligence & Data Science' , 'Artificial Intelligence & Data Science'),
    ('Computer Science Engineering','Computer Science Engineering'),
    ('Electrical and Electronic Engineering','Electrical and Electronic Engineering'),
    ('Electronics and Communication Engineering','Electronics and Communication Engineering'),
    ('Cyber security','Cyber security'),('Mechanical Engineering','Mechanical Engineering')
)

class Folder(models.Model):
    foldername = models.CharField(max_length=50)
    folderdesc = models.CharField(max_length=255)
    folderuser = models.ForeignKey(User, on_delete=models.CASCADE)
    
    def __str__(self):
        return self.foldername
    def delete_folder(self):
        self.delete()

class File(models.Model):
    filetitle = models.CharField(max_length=50)
    folder = models.ForeignKey(Folder, on_delete=models.CASCADE)
    file = models.FileField(upload_to="Files")
    def __str__(self):
        return self.filetitle
    def delete_file(self):
        self.file.delete()
        self.delete()

class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    year = models.CharField(choices=YEAR_CHOICES,max_length=50)
    degree_department = models.CharField(choices=Depat_CHOICES,max_length=100)
    date_of_birth = models.DateField()
    sex = models.CharField(max_length=10, choices=(('Male', 'Male'), ('Female', 'Female')))
    linkedin_link =models.URLField(blank=True)
    github_link = models.URLField(blank=True)
    website_link = models.URLField(blank=True)
    profile_image = models.ImageField(upload_to='profile_images/', blank=True, null=True)
    phone = models.CharField(max_length=15)
    email = models.EmailField()
    about = models.TextField()

    def __str__(self):
        return f"{self.first_name} {self.last_name}"


class ProfileVisitLink(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    generated_link = models.CharField(max_length=8, unique=True)  # Assuming the link is a string of 8 characters
    qr_code_image = models.ImageField(upload_to='qr_codes/', null=True, blank=True)

    def __str__(self):
        return f"Link for {self.user.username}: {self.generated_link}"
        
class QRCode(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    url = models.URLField()
    qr_code_image = models.ImageField(upload_to='qr_codes/')

    def __str__(self):
        return f"QR Code for {self.url} (User: {self.user.username})"

MyPortFolios/PortFolio/views.py
from django.shortcuts import render, redirect ,get_object_or_404
from .forms import SignUpForm, LoginForm ,StudentProfileForm
from django.contrib.auth import authenticate, login
from .models import RequestToAdmin  ,Folder,File ,Student 
from django.contrib.auth.decorators import login_required
from django.views.generic import View
from django.http import JsonResponse
from django.contrib import messages
from django.contrib.auth.models import User
from PortFolio.models import User 
from django.db.models import Count 
from django.http import HttpResponse
from .models import ProfileVisitLink
import uuid
from django.urls import reverse
from django.utils.crypto import get_random_string
import qrcode
from io import BytesIO
from django.contrib.auth import logout
from django.core.exceptions import ObjectDoesNotExist
from PIL import Image


def home(request):
    if request.user.is_authenticated:
        try:
            student = request.user.student 
            profile_visit_link = ProfileVisitLink.objects.filter(user=request.user).last()
            generated_link = profile_visit_link.generated_link if profile_visit_link else None
            return render(request, 'home.html', {'student': student, 'generated_link': generated_link})
        except Student.DoesNotExist:
            return render(request, 'home.html', {'error_message': 'Student profile not found'})
    else:
        return render(request, 'home.html', {'error_message': 'Please log in'})


def delete_profile_image(request):
    if request.method == 'POST':
        profile_id = request.POST.get('profile_id')
        try:
            profile = UserProfile.objects.get(id=profile_id)
            # Clear the profile image field and save the profile
            profile.profile_image = None
            profile.save()
            return redirect('profile')
        except UserProfile.DoesNotExist:
            pass
    return redirect('profile')

@login_required
def dashboard(request):
    try:
        student = request.user.student
        user_id = request.user.id
        folders_with_file_count = Folder.objects.filter(folderuser_id=user_id).annotate(num_files=Count('file'))
        folder_count = Folder.objects.filter(folderuser_id=user_id).count()
        file_count = File.objects.filter(folder__folderuser_id=user_id).count()
        profile_visit_link = ProfileVisitLink.objects.filter(user=request.user).last()
        generated_link = profile_visit_link.generated_link if profile_visit_link else None

        context = {
            'student': student,
            'user': request.user,
            'folders_with_file_count': folders_with_file_count,
            'folder_count': folder_count,
            'file_count': file_count,
            'generated_link': generated_link,
        }
        return render(request, 'dashboard.html', context)
    except ObjectDoesNotExist:
        error_message = 'Student profile not found'
        return render(request, 'dashboard.html', {'error_message': error_message})

def activity(request):  
    if request.user.is_authenticated:
        try:
            student = Student.objects.get(user=request.user)
            folder = Folder.objects.filter(folderuser=request.user)
            profile_visit_link = ProfileVisitLink.objects.filter(user=request.user).last()
            generated_link = profile_visit_link.generated_link if profile_visit_link else None

            context = {'folder': folder, 'student': student, 'user': request.user,
                       'generated_link': generated_link}
            return render(request, 'activity.html', context)
        except ObjectDoesNotExist:
            return render(request, 'error.html', {'error_message': 'Student matching query does not exist.'})
    else:
        return redirect('homepage')

# def activity(request):
#     student = Student.objects.get(user=request.user)
#     context = {
#         'student': student,
#         'user': request.user,
#     }
#     return render(request ,'activity.html',context)

# def activity(request):  
#     if request.user.is_authenticated:
#         student = Student.objects.get(user=request.user)
#         folder = Folder.objects.filter(folderuser=request.user)
#         context = {'folder':folder , 'student': student,
#             'user': request.user,}
#         return render(request,'activity.html',context)
#     else:
#         return redirect('homepage')

def resume(request):
    student = Student.objects.get(user=request.user)
    context = {
        'student': student,
        'user': request.user,
    }
    return render(request ,'resume.html',context)

def waiting_page(request):
    return render(request, 'waiting_page.html')

def decline_page(request):
    return render(request, 'decline_page.html')

def admin(request):
    # Retrieve requests from students
    requests = RequestToAdmin.objects.all()
    return render(request, 'staff/staffadmin.html', {'requests': requests})

def approve_request(request, request_id):
    request_object = RequestToAdmin.objects.get(id=request_id)
    student = request_object.student
    student.request_approved = True
    student.request_declined = False
    student.save()
    request_object.delete()  
    return redirect('adminpage')

def decline_request(request, request_id):
    request_object = RequestToAdmin.objects.get(id=request_id)
    student = request_object.student
    student.request_approved = False
    student.request_declined = True
    student.save()
    # You may want to add additional logic here, such as sending notifications to the student
    request_object.delete()  # Delete the request after it's declined
    return redirect('adminpage')
    
def register(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.set_password(form.cleaned_data['password1'])
            user.role = form.cleaned_data['role']
            user.save()
            messages.success(request, 'Registration successful. Please login.')
            return redirect('login_view')
        else:
            messages.error(request, 'Registration failed. Please check the form.')
    else:
        form = SignUpForm()
    return render(request, 'register.html', {'form': form})

def login_view1(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if user.role == 'admin':
                    return redirect('adminpage')
                elif user.role == 'student':
                    existing_request = RequestToAdmin.objects.filter(student=user).exists()
                    if not existing_request:
                        RequestToAdmin.objects.create(student=user, message="Please process my request.")
                    if user.request_approved:
                        return redirect('homepage')
                    elif user.request_declined:
                        return redirect('login_view') 
                    else:
                        return redirect('decline_page')
                else:
                    pass
            else:
                pass
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})

def login_view(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password')
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                if user.role == 'admin':
                    messages.success(request, 'Admin login successful.')
                    return redirect('adminpage')
                elif user.role == 'student':
                    existing_request = RequestToAdmin.objects.filter(student=user).exists()
                    if not existing_request:
                        RequestToAdmin.objects.create(student=user, message="Please process my request.")
                    if user.request_approved:
                        messages.success(request, 'Student login successful.')
                        return redirect('homepage')
                    else:
                        messages.info(request, 'Student login successful. Waiting for approval.')
                        return redirect('login_view')
            else:
                messages.error(request, 'Invalid username or password.')
    else:
        form = LoginForm()
    # Provide the form to the template context
    return render(request, 'login.html', {'form': form})

def student(request):
    return render(request,'student.html')

def student_list(request):
    students = Student.objects.all()
    return render(request, 'staff/student.html', {'students': students})

def student_details(request, student_id):
    student = Student.objects.get(id=student_id)
    return render(request, 'staff/student_details.html', {'student': student})

def folder(request,folderid):
    if request.user.is_authenticated:
        folder_user = Folder.objects.get(id=folderid)
        files = File.objects.filter(folder=folder_user)
        context = {'folderid':folderid,'files':files}
        if request.method == 'POST':
            file_user = request.FILES.get('file')
            file_title = request.POST.get('filetitle')
            fileadd = File.objects.create(filetitle=file_title,file=file_user,folder=folder_user)
        return render(request,'folder.html',context)
    else:
        return redirect('homepage')

def addfolder(request):
   if request.method == 'POST':
       folder_name = request.POST['foldername']

MyPortFolios/PortFolio/templates/staff/base.html
<!doctype html>
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>MyPortFolio - {% block title %}{% endblock title %}</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="{% static 'assets/img/logo1.jpg' %}" rel="icon">
  <link href="{% static 'assets/img/logo1.jpg' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="{% static 'assets/vendor/aos/aos.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/bootstrap-icons/bootstrap-icons.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/boxicons/css/boxicons.min.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.snow.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/quill/quill.bubble.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/remixicon/remixicon.css' %}" rel="stylesheet">
  <link href="{% static 'assets/vendor/simple-datatables/style.css' %}" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link id="theme-style" rel="stylesheet" href="{% static 'assets/css/pillar-2.css' %}">
  <link href="{% static 'assets/css/style.css' %}" rel="stylesheet">
  <link href="{% static 'assets/css/home.css' %}" rel="stylesheet">

</head>

<body  >
  
<header id="header" class="header fixed-top d-flex align-items-center " >

    <div class="d-flex align-items-center justify-content-between">
      <a href="" class="logo d-flex align-items-center">
        <img src="{% static 'assets/img/logo1.jpg'%}" alt="">
        <span class="d-none d-lg-block">My PortFolio</span>
      </a>
      <i class="bi bi-list toggle-sidebar-btn"></i>
    </div><!-- End Logo -->

    <div class="search-bar">
      <form class="search-form d-flex align-items-center" method="POST" action="#">
        <input type="text" name="query" placeholder="Search" title="Enter search keyword">
        <button type="submit" title="Search"><i class="bi bi-search"></i></button>
      </form>
    </div><!-- End Search Bar -->
    <div>
      <img src="{% static 'assets/img/logo1.jpg'%}" alt="" style="width: 4%;">

      <img src="{% static 'assets/img/clg name.jpg'%}" alt="" style="width: 30%;">
    </div>
    <nav class="header-nav ms-auto">

  
      <ul class="d-flex align-items-center">

        <li class="nav-item d-block d-lg-none">
          <a class="nav-link nav-icon search-bar-toggle " href="#">
            <i class="bi bi-search"></i>
          </a>
        </li><!-- End Search Icon-->

      

        <li class="nav-item dropdown pe-3">

          <a class="nav-link nav-profile d-flex align-items-center pe-0" href="#" data-bs-toggle="dropdown">
            
            <span class="d-none d-md-block dropdown-toggle ps-2">{{ user.username }}</span>
          </a><!-- End Profile Iamge Icon -->

          <ul class="dropdown-menu dropdown-menu-end dropdown-menu-arrow profile">
            <li class="dropdown-header">
              <h6>{{ user.username }}</h6>
              <span>{{ user.get_role_display }}</span>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-person-fill"></i>
                <span>My Profile</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="users-profile.html">
                <i class="bi bi-file-earmark-text-fill"></i>
                <span>Resume</span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="pages-faq.html">
                <i class="bi bi-question-circle"></i>
                <span></span>
              </a>
            </li>
            <li>
              <hr class="dropdown-divider">
            </li>

            <li>
              <a class="dropdown-item d-flex align-items-center" href="#">
                <i class='bx bxs-log-out'></i>
                <span>Sign Out</span>
              </a>
            </li>

          </ul><!-- End Profile Dropdown Items -->
        </li><!-- End Profile Nav -->

      </ul>
    </nav><!-- End Icons Navigation -->

</header>

<aside id="sidebar" class="sidebar " >
    <ul class="sidebar-nav" id="sidebar-nav">
      <li class='nav-item'>
        <div class="card ">
            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center">

              {% comment %} <img src="{% static 'assets/img/profile-img.jpg' %}" alt="Profile" class="rounded-circle"><br> {% endcomment %}
              <h4>{{ user.username }}</h4>
              <h5>{{ user.get_role_display }}</h5>
              <div class="social-links mt-2">
{% comment %}                 
                <a href="#" class="twitter"><i class="bi bi-geo-alt-fill"></i></a>
                <a href="#" class="mail"><i class="bi bi-envelope-fill"></i></a>
                <a href="#" class="github"><i class="bi bi-github"></i></a>
                <a href="#" class="linkedin"><i class="bi bi-linkedin"></i></a> {% endcomment %}
              </div>
            </div>
        </div>
      </li>

      

      <li class="nav-item">
        <a class="nav-link collapsed" href="{% url 'adminpage' %}">
          <i class="bi bi-person-fill"></i>
          <span>Request list</span>
        </a>
      </li>

      <li class="nav-item">
        <a class="nav-link collapsed" href='{% url "student_list" %}'>
          <i class="bi bi-bar-chart-fill"></i>
          <span>Student List</span>
        </a>
      </li>

      
        {% comment %} <li class=" nav-item ">
            <div class="card">
            <div class="card-body profile-card pt-4 d-flex flex-column align-items-center ">
 
                <img src="{% static 'assets/img/Qrcode.jpg' %}" alt="Profile" class="cart">
                <span class="badge bg-secondary"><i class="bi bi-qr-code-scan"></i> Qr Code Profile</span>

            </div>
          </div>
        </li>  {% endcomment %}

    </ul>

</aside>

{% block main-content %}{% endblock main-content %}

  
  <!-- Vendor JS Files -->
  <script src="{% static 'assets/vendor/aos/aos.js' %}"></script>
  <script src="{% static 'assets/vendor/apexcharts/apexcharts.min.js' %}"></script>
  <script src="{% static 'assets/vendor/bootstrap/js/bootstrap.bundle.min.js'%}"></script>
  <script src="{% static 'assets/vendor/chart.js/chart.umd.js'%}"></script>
  <script src="{% static 'assets/vendor/echarts/echarts.min.js'%}"></script>
  <script src="{% static 'assets/vendor/quill/quill.min.js'%}"></script>
  <script src="{% static 'assets/vendor/simple-datatables/simple-datatables.js'%}"></script>
  <script src="{% static 'assets/vendor/tinymce/tinymce.min.js'%}"></script>
  <script src="{% static 'assets/vendor/php-email-form/validate.js'%}"></script>
  <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>

  <!-- Template Main JS File -->
  <script src="{% static 'assets/js/main.js'%}"></script>


</body>

</html>

MyPortFolios/PortFolio/templates/staff/student.html
{% extends 'staff/base.html' %}
{% load static %}
{% block title %}Staff Admin{% endblock title %}

{% block main-content %}
<main id="main" class="main">
    <div class="pagetitle">
        <h1>Student List</h1>
    </div>
    <section class="section dashboard">
        <div class="row">
            <div class="col-lg-10">
                <div class="row">
                    {% for student in students %}
                    <div class="col-xxl-4">
                        <div class="card info-card sales-card">
                            <div class="card-body">
                                <h5 class="card-title">User | {{ forloop.student }}</h5>
                                <div class="d-flex align-items-center">
                                    <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                        <i class="bi bi-cart"></i>
                                    </div>
                                    <div class="ps-3">
                                        <h6>{{ student.first_name }} {{ student.last_name }}</h6>
                                        <a href="{% url 'student_details' student.id %}" class="btn btn-outline-primary">View Profile</a>
                                        <span class="text-muted small pt-2 ps-1">{{ student.register_number }}</span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </section>
</main>



{% endblock main-content %}
                
  

MyPortFolios/PortFolio/templates/staff/student_details.html
{% extends 'staff/base.html' %}
{% load static %}
{% block title %}Staff Admin{% endblock title %}

{% block main-content %} 


  <main id="main" class="main">

    <div class="pagetitle">
      <h1>Studemt Details</h1>
    </div><!-- End Page Title -->

    <section class="section contact">   
      <div class='row'>
        <div class="col-xl-6">
                  <div class="card info-card sales-card">
                    <div class="container">
                      <div class="pagetitle">
                        <h1>Folders</h1>    
                      </div>
                      <div class="row">
                        {% for folder in student.user.folder_set.all %}
                          <div class="col-md-6">
                            <div class="card info-card sales-card">
                              <div class="card-body">
                                <h5 class="card-title">{{ folder.foldername }} <span>| </span>{{ forloop.counter }}</h5>
                                <div class="d-flex align-items-center">
                                  <div class="card-icon rounded-circle d-flex align-items-center justify-content-center">
                                    <i class="bi bi-folder-fill"></i>
                                  </div>
                                  <div class="ps-3">
                                    <h6>{{ folder.folderdesc }}</h6>
                                  </div>
                                </div>
                                <div class="mt-3">
                                  <h6>Files:</h6>
                                  <ul class="list-group">
                                    {% for file in folder.file_set.all %}
                                      <li class="list-group-item">{{ file.filetitle }} - <a href="{{ file.file.url }}">Download</a></li>
                                    {% endfor %}
                                  </ul>
                                </div>
                              </div>
                            </div>
                          </div>
                        {% endfor %}
                      </div>
                    </div>
                  </div>
        </div>          
        
        <div class="col-xl-5">
          <div class="card p-4">
            <h2>{{ student.first_name }} {{ student.last_name }}</h2>
            <p>Year: {{ student.year }}</p>
            <p>Department: {{ student.degree_department }}</p>
            <p>Date of Birth: {{ student.date_of_birth }}</p>
            <p>Sex: {{ student.sex }}</p>
            <p>LinkedIn: <a href="{{ student.linkedin_link }}">{{ student.linkedin_link }}</a></p>
            <p>Github: <a href="{{ student.github_link }}">{{ student.github_link }}</a></p>
            <p>Website: <a href="{{ student.website_link }}">{{ student.website_link }}</a></p>
            <p>Phone: {{ student.phone }}</p>
            <p>Email: {{ student.email }}</p>
            <p>About: {{ student.about }}</p>

          </div>
        </div>
      
      </div>
      
    </section>
  </main>
{% endblock main-content %}
                
  